"""
training_data.py
------------------
Hand-curated, labeled dataset of meeting utterances used to TRAIN the
Multinomial Naive Bayes tone classifier (see tone_classifier.py).

Classes:
    positive   -> collaborative, appreciative, encouraging tone
    neutral    -> factual / informative, no strong emotional charge
    negative   -> disappointed, frustrated, worried tone
    aggressive -> confrontational, hostile, blaming tone
    anxious    -> uncertain, hesitant, nervous tone

This dataset is intentionally bundled inside the project (no external
download / API needed) so the model trains instantly, offline, and
deterministically on every fresh install.
"""

TRAINING_DATA = [
    # ---------------- positive ----------------
    ("Great work everyone, we hit the sprint goal ahead of schedule.", "positive"),
    ("I really appreciate the effort the team put into this release.", "positive"),
    ("This is excellent progress, thank you all for the hard work.", "positive"),
    ("I'm thrilled with how the demo went today, great job team.", "positive"),
    ("Thanks for jumping in and fixing that so quickly, awesome work.", "positive"),
    ("I love the direction this project is heading, very promising.", "positive"),
    ("Well done on closing the client deal, that's a huge win for us.", "positive"),
    ("The new design looks fantastic, I'm impressed by the polish.", "positive"),
    ("I'm confident we'll deliver this on time, the team is doing great.", "positive"),
    ("Congratulations to the QA team for catching that bug early.", "positive"),
    ("This collaboration between design and engineering worked really well.", "positive"),
    ("I appreciate everyone staying late to help us ship this feature.", "positive"),
    ("Fantastic presentation, very clear and well organised.", "positive"),
    ("I'm happy with the results of the A/B test, conversions are up.", "positive"),
    ("Great initiative, let's keep this momentum going into next quarter.", "positive"),
    ("Thank you for the detailed update, this is exactly what we needed.", "positive"),
    ("The customer feedback has been overwhelmingly positive this month.", "positive"),
    ("Nice catch on that edge case, saved us from a production issue.", "positive"),
    ("I'm proud of how the team handled the outage yesterday.", "positive"),
    ("This roadmap looks solid, good balance of features and stability.", "positive"),
    ("Everyone did a wonderful job pulling this launch together.", "positive"),
    ("I'm grateful for the support during the migration, smooth process.", "positive"),
    ("Really good energy in this meeting, let's carry it forward.", "positive"),
    ("The onboarding flow is much smoother now, great improvement.", "positive"),
    ("I think this partnership will be a great opportunity for growth.", "positive"),
    ("Awesome debugging session, we resolved it faster than expected.", "positive"),
    ("Kudos to the support team for the quick turnaround on tickets.", "positive"),
    ("This is a strong proposal, I'm on board with moving forward.", "positive"),
    ("The metrics look great this quarter, well above target.", "positive"),
    ("I'm excited about the new feature set we're shipping next sprint.", "positive"),
    ("Solid teamwork today, everyone contributed some great ideas.", "positive"),
    ("The client was very happy with the delivery, great news.", "positive"),
    ("This update makes the workflow so much easier, thank you.", "positive"),
    ("I'm optimistic about hitting our Q3 targets given this pace.", "positive"),
    ("Really appreciate the clear documentation you put together.", "positive"),
    ("Great alignment across teams today, very productive discussion.", "positive"),
    ("The launch went smoothly, no incidents reported, great job.", "positive"),
    ("I'm happy to support this plan, it looks well thought out.", "positive"),
    ("Thanks for the quick review, your feedback was really helpful.", "positive"),
    ("This is a promising start, let's build on this success.", "positive"),

    # ---------------- neutral ----------------
    ("Let's move to the next agenda item, the budget review.", "neutral"),
    ("The report is due by Friday end of day.", "neutral"),
    ("We will schedule the next meeting for Tuesday at 10am.", "neutral"),
    ("Here is a quick update on the current sprint status.", "neutral"),
    ("The database migration is scheduled for this weekend.", "neutral"),
    ("Please review the attached document before the call.", "neutral"),
    ("The release notes have been shared in the team channel.", "neutral"),
    ("We are currently in the testing phase of the project.", "neutral"),
    ("The vendor contract renewal is up for discussion next week.", "neutral"),
    ("I will send the meeting minutes after this call ends.", "neutral"),
    ("The API documentation has been updated to version two.", "neutral"),
    ("Our next milestone is the beta release in three weeks.", "neutral"),
    ("The server maintenance window is from midnight to 2am.", "neutral"),
    ("Let's go through the action items from last week.", "neutral"),
    ("The finance team will present the quarterly numbers.", "neutral"),
    ("We need two more approvals before this can proceed.", "neutral"),
    ("The design mockups are attached in the shared folder.", "neutral"),
    ("This feature is currently in the backlog for next sprint.", "neutral"),
    ("The team standup will start in five minutes.", "neutral"),
    ("We are collecting requirements for the next phase.", "neutral"),
    ("The ticket has been assigned to the backend team.", "neutral"),
    ("Please add your availability to the shared calendar.", "neutral"),
    ("The staging environment will be refreshed tonight.", "neutral"),
    ("We have three open items to close before the release.", "neutral"),
    ("The audit is scheduled for the second week of next month.", "neutral"),
    ("Let's summarise the decisions made in today's meeting.", "neutral"),
    ("The new hire will join the team starting next Monday.", "neutral"),
    ("This slide covers the technical architecture overview.", "neutral"),
    ("We will follow up over email with the finalised dates.", "neutral"),
    ("The current sprint has twelve story points remaining.", "neutral"),
    ("Access requests should be submitted through the portal.", "neutral"),
    ("The dashboard will be updated with the latest figures tomorrow.", "neutral"),
    ("We are reviewing three vendors for the new tooling.", "neutral"),
    ("The compliance checklist needs to be completed by Friday.", "neutral"),
    ("Let's table this discussion and revisit it next week.", "neutral"),
    ("The project timeline has three remaining phases.", "neutral"),
    ("I will circulate the notes after the meeting.", "neutral"),
    ("The next release is version 2.4, planned for next month.", "neutral"),
    ("We need to confirm the meeting room for tomorrow.", "neutral"),
    ("The invoice has been forwarded to the accounts team.", "neutral"),

    # ---------------- negative ----------------
    ("I'm disappointed that we missed the deadline again.", "negative"),
    ("This delay is really going to hurt our credibility with the client.", "negative"),
    ("I'm concerned we are not going to catch up on the backlog.", "negative"),
    ("The rollout was messy and caused a lot of confusion.", "negative"),
    ("We keep running into the same problems every sprint.", "negative"),
    ("I'm frustrated that this bug wasn't caught before release.", "negative"),
    ("This is the third time we've slipped the launch date.", "negative"),
    ("The feedback from the client was pretty disappointing.", "negative"),
    ("I'm worried about the quality of the last release.", "negative"),
    ("We are behind schedule and the team seems overwhelmed.", "negative"),
    ("Honestly, this outcome is not what we expected at all.", "negative"),
    ("There are too many unresolved issues going into launch.", "negative"),
    ("I don't think this plan is going to work out well.", "negative"),
    ("The communication between teams has been really poor lately.", "negative"),
    ("This mistake could have been avoided with better testing.", "negative"),
    ("I'm not happy with how this project has been handled.", "negative"),
    ("The numbers this quarter are disappointing across the board.", "negative"),
    ("We wasted a lot of time chasing the wrong problem.", "negative"),
    ("This keeps happening and nobody seems to have a fix.", "negative"),
    ("I'm afraid this outage is going to damage customer trust.", "negative"),
    ("The scope keeps changing and it's slowing everyone down.", "negative"),
    ("This is becoming a recurring problem that we can't ignore.", "negative"),
    ("I'm troubled by how disorganised this launch has been.", "negative"),
    ("The team morale seems low after the last two setbacks.", "negative"),
    ("We are struggling to keep up with the current workload.", "negative"),
    ("This approach clearly isn't working, we need to rethink it.", "negative"),
    ("I'm upset that this wasn't flagged to me earlier.", "negative"),
    ("The client escalated this issue and it's not looking good.", "negative"),
    ("We have lost a lot of ground because of this delay.", "negative"),
    ("This is a difficult situation and morale is pretty low.", "negative"),

    # ---------------- aggressive ----------------
    ("This is completely unacceptable, someone needs to explain now.", "aggressive"),
    ("I'm done waiting, fix this immediately or heads will roll.", "aggressive"),
    ("Whose fault is this? Someone clearly dropped the ball here.", "aggressive"),
    ("Stop making excuses and just get it done, no more delays.", "aggressive"),
    ("This is ridiculous, how did nobody catch this before release.", "aggressive"),
    ("I don't want to hear another excuse, just fix it.", "aggressive"),
    ("You never listen in these meetings, this keeps happening.", "aggressive"),
    ("Honestly this whole approach has been a complete disaster.", "aggressive"),
    ("I demand an explanation for why this was never escalated.", "aggressive"),
    ("This is a waste of everyone's time, we need real answers now.", "aggressive"),
    ("Frankly, the incompetence on this project is unbelievable.", "aggressive"),
    ("Someone needs to take the blame for this failure right now.", "aggressive"),
    ("Enough talk, I want results by end of day, no exceptions.", "aggressive"),
    ("This kind of sloppy work is simply not acceptable anymore.", "aggressive"),
    ("I'm sick of repeating myself, why is this still not fixed.", "aggressive"),
    ("Nobody in this team seems to take ownership of anything.", "aggressive"),
    ("This is outrageous, we agreed on this weeks ago and nothing moved.", "aggressive"),
    ("You need to stop pointing fingers and own your mistakes.", "aggressive"),
    ("I've had enough of these constant delays, this must stop today.", "aggressive"),
    ("This is a pathetic excuse for a status update, be serious.", "aggressive"),

    # ---------------- anxious ----------------
    ("I'm not totally sure this is going to work, I'm a bit worried.", "anxious"),
    ("Maybe we should double check, I'm not confident about the numbers.", "anxious"),
    ("I think this could go wrong, I'm honestly a little nervous about it.", "anxious"),
    ("I'm not sure if we have enough time, this feels risky to me.", "anxious"),
    ("Perhaps we're moving too fast, I'm a little uneasy about the plan.", "anxious"),
    ("I guess it could work, but I'm not entirely confident about it.", "anxious"),
    ("I'm worried we might be underestimating how hard this will be.", "anxious"),
    ("Honestly I'm a bit anxious about presenting this to the board.", "anxious"),
    ("I'm not certain this approach is safe, can we get a second opinion.", "anxious"),
    ("This makes me nervous, I don't think we've tested this enough.", "anxious"),
    ("I could be wrong, but something about this timeline worries me.", "anxious"),
    ("I'm hesitant to commit to this date, there are too many unknowns.", "anxious"),
    ("Maybe I'm overthinking it, but this feels like it could fail.", "anxious"),
    ("I'm a little unsure how the client will react to this change.", "anxious"),
    ("I don't feel fully prepared for this review, I'm a bit stressed.", "anxious"),
    ("Not sure if this is the right call, I keep second guessing it.", "anxious"),
    ("I'm slightly worried we haven't accounted for the edge cases.", "anxious"),
    ("This uncertainty is making me nervous about the launch date.", "anxious"),
    ("I hope this works, but I honestly have some doubts about it.", "anxious"),
    ("I'm a bit apprehensive about rolling this out to everyone at once.", "anxious"),
]
